name: Run Query
on:
  workflow_dispatch: # 这个代表在网页上生成一个手动运行的按钮

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Run Tool
        env:
          CRENDENTIALS: ${{ secrets.CRENDENTIALS }}
        run: cargo run --release

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: latest-mailboxes
          path: result/mailboxes.csv
